// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQaKYVH1wqI5lq7Wvn03J-IEM_y6OUSTY',
    appId: '1:589763065955:web:ac806b1585c607af2fe056',
    messagingSenderId: '589763065955',
    projectId: 'amipet-7930d',
    authDomain: 'amipet-7930d.firebaseapp.com',
    storageBucket: 'amipet-7930d.firebasestorage.app',
    measurementId: 'G-SF3TFDXS2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQaKYVH1wqI5lq7Wvn03J-IEM_y6OUSTY',
    appId:
        '1:589763065955:android:ac806b1585c607af2fe056', // Esto se actualizará cuando configures Android
    messagingSenderId: '589763065955',
    projectId: 'amipet-7930d',
    storageBucket: 'amipet-7930d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrwnxqnGinkl70WWa9l0KGX517pxzbZe0',
    appId: '1:589763065955:ios:0d1ff092c81ef35e2fe056',
    messagingSenderId: '589763065955',
    projectId: 'amipet-7930d',
    storageBucket: 'amipet-7930d.firebasestorage.app',
    iosClientId:
        '589763065955-n0q5t9omvt720kgoj7v9ordfcsde0hoj.apps.googleusercontent.com',
    iosBundleId: 'bo.com.amipet.amipet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrwnxqnGinkl70WWa9l0KGX517pxzbZe0',
    appId: '1:589763065955:ios:0d1ff092c81ef35e2fe056',
    messagingSenderId: '589763065955',
    projectId: 'amipet-7930d',
    storageBucket: 'amipet-7930d.firebasestorage.app',
    iosClientId:
        '589763065955-n0q5t9omvt720kgoj7v9ordfcsde0hoj.apps.googleusercontent.com',
    iosBundleId: 'bo.com.amipet.amipet',
  );
}
